### ISSUE TITLE
Raw HTML as part of VDOM and escaping

### ISSUE THREAD

**Issue by pauleveritt** [jviide/htm.py#12]
This is part `htm.py` and part `viewdom` for serializing. Asking here.

I have some cases (Markdown rendering, Sphinx body,pygments code blocks) where I have HTML generated outside of the template/component that aren't really VDOM. But they needed to be inserted into the serialized result.

This is common in other template systems, either through a filter that says "safe" or wrapping the value in a `SafeMarkup` class.

I'm thinking about changing the renderer to [detect an instance of a marker class](https://github.com/pauleveritt/viewdom/blob/master/src/viewdom/h.py#L60) and not calling `escape()`.

From a "theory of VDOM" perspective, does this make sense?

**Comment by jviide** [comment]
Yes, sounds good 🙂 Another way of doing that would probably be React-style special [`dangerouslySetInnerHTML` prop](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml), but I personally prefer the the SafeMarkup-style approach. A special shoutout to @oherrala's [Medium post on the topic](https://medium.com/sensorfu/using-static-typing-to-protect-against-code-injection-attacks-353002ca6f2b)!

**Comment by pauleveritt** [comment]
I guess I should just make `MarkupSafe` a dependency of `viewdom` and sniff for instances when rendering?

**Comment by rmorshea** [comment]
@pauleveritt not sure if this is what you're looking for, but in [IDOM](https://github.com/rmorshea/idom) I did the following to convert HTML strings into VDOM with the option to pass transform functions that are allowed to modify the VDOM before its returned: https://github.com/rmorshea/idom/blob/master/idom/tools.py#L70

**Comment by pauleveritt** [comment]
Thanks a bunch for the pointer. Very useful and lots of interesting stuff in IDOM.

**Comment by pauleveritt** [comment]
@rmorshea Mind if I copy/paste `tools.py` and `test_tools.py` and give you credit?

Also, would you have a moment to review my `viewdom` docs and give any feedback?

**Comment by rmorshea** [comment]
@pauleveritt feel free to do so. Though, looking at `viewdom` a bit more and assuming the transformation aspect of `html_to_vdom` is what's of interest, it might be more efficient to allow transform functions to modify the values passed from `htm` rather than rendering to HTML then back to VDOM using `html_to_vdom` for the transformation and then back to HTML again.

I think I've mentioned this before, but another feature of IDOM that may be worth looking into is its JSX-style dynamic transpiler for Python. This has two benefits:

1. Better performance - getting VDOM out of JSX no longer requires parsing HTML at runtime or accessing stackframes.
2. The syntax I've chosen for the transpiler actually allows standard static analysis tools in the Python ecosystem to evaluate expressions within the JSX templates without any modifications or plugins to those tools.

Here's a quick example of the syntax. In short the transpiler looks for expression of the from `html(f"...")` and transforms them appropriately.

```python
# dialect=html
from idom import html

message = "hello world!"
attrs = {"height": "10px", "width": "10px"}
model = html(f"<div ...{attrs}><p>{message}</p></div>")

assert model == {
    "tagName": "div",
    "attributes": {"height": "10px", "width": "10px"},
    "children": [{"tagName": "p", "children": ["hello world!"]}],
}
```


https://idom.readthedocs.io/en/latest/extra-features.html#python-language-extension

**Comment by pauleveritt** [comment]
@rmorshea Perhaps we should move this conversation to a ticket in `viewdom`?
